version: "3.1"
services:
    #Database Activity Monitoring (DAM)
    st-agent:
        image: sematext/agent:latest
        privileged: true
        environment:
            - INFRA_TOKEN=153295d6-b518-415a-8f11-ab3e84262228
            - SERVER_BASE_URL=https://spm-receiver.sematext.com
            - LOGS_RECEIVER_URL=https://logsene-receiver.sematext.com
            - EVENT_RECEIVER_URL=https://event-receiver.sematext.com
            - COMMAND_SERVER_URL=https://command.sematext.com
        cap_add:
            - SYS_ADMIN
        restart: always
        volumes:
            - /:/hostfs:ro
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro
            - /var/run/:/var/run
            - /sys/kernel/debug:/sys/kernel/debug
            - /sys:/host/sys:ro
            - /dev:/hostfs/dev:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
    www:
        build: .
        container_name: www
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
        depends_on:
                - db
    db:
        image: mysql
        container_name: db
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: test 
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test     
            ST_MONITOR_MYSQL_DB_USER: "spm-user" # For Database Activity Monitoring
            ST_MONITOR_MYSQL_DB_PASSWORD: "spm-password" # FOR Database Activity Monitoring 
        ports: 
            - "33306:3306"        
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
    phpmyadmin: #Add this container
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - 8000:80
        environment:
            PMA_HOST: 'db'
            PMA_PORT: '3306'
        depends_on:
            - db
volumes:
    persistent: